services:
  immich-albums-frontend:
    build: ./frontend
    container_name: immich-albums-frontend
    ports:
      - "15100:15100"
    depends_on:
      - immich-albums-backend
    restart: unless-stopped

  immich-albums-backend:
    build: ./backend
    container_name: immich-albums-backend
    ports:
      - "15000:15000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
